"use client";
import { useEffect, useState } from "react";

type Props={questId:number;onClose:()=>void;onComplete:()=>void};
const titles:{[key:number]:string}={1:"Den försvunna signalen",2:"Synkronisera nätverket",3:"Pixeljägaren",4:"Boss raid: Blackout"};
const routes:{[key:number]:string}={1:"Rörlig ledartagg · nedre foajén / övre foajén / Skeppet",2:"Kapphängningen → fejkade eldstaden → TV-spelen under läktaren",3:"Huvudentrén utomhus → soffgruppen i nedre foajén",4:"Sällskapsspelen vid gradängen → TV-hörnan → scenens publika sida"};

export default function CoreQuestGames({questId,onClose,onComplete}:Props){
  const[stage,setStage]=useState(0);const[wrong,setWrong]=useState(false);const[done,setDone]=useState(false);const[ready,setReady]=useState([false,false,false]);const[count,setCount]=useState(10);const[scans,setScans]=useState([false,false,false]);const[cells,setCells]=useState([false,false,false]);
  useEffect(()=>{if(questId!==2||stage!==1||count<=0)return;const t=setTimeout(()=>setCount(c=>c-1),1000);return()=>clearTimeout(t)},[questId,stage,count]);
  const finish=()=>{setDone(true);onComplete()};
  const resetSync=()=>{setStage(0);setReady([false,false,false]);setScans([false,false,false]);setCount(10)};
  const scanNode=(i:number)=>{if(count<=0)return;const next=scans.map((v,n)=>n===i?true:v);setScans(next);if(next.every(Boolean))finish()};
  return <div className="modal-backdrop"><section className="core-game"><button className="close" onClick={onClose}>×</button><div className="mission-bar"><span>AKTIVT UPPDRAG</span><b>+{[250,600,180,1200][questId-1]} Chip</b></div><h2>{titles[questId]}</h2><div className="route-banner"><small>UPPDRAGSRUTT</small><b>{routes[questId]}</b><span>Endast publika ytor. Sovsalar, toaletter, kök, kontor och teknik/admin är förbjudna.</span></div>
  {done?<div className="game-result"><div className="result-mark success">✓</div><h3>Uppdrag slutfört!</h3><p>Resultatet är registrerat. Du kan nu återvända till uppdragslistan.</p><button className="primary full" onClick={onClose}>HÄMTA CHIP & STÄNG</button></div>:<>
  {questId===1&&<div className="core-body">{stage===0&&<><div className="clue-screen"><small>VANDRANDE LEDTRÅD</small><p>”Jag hjälper spelare men sitter sällan själv vid en station. Signalen följer mig mellan foajéerna och Skeppet.”</p></div><div className="objective"><b>DITT MÅL</b><span>Hitta ledaren som just nu bär signalbrickan på sitt nyckelband. Fråga inte vem det är – använd ledtråden och håll utkik i de publika zonerna.</span></div><button className="primary full" onClick={()=>setStage(1)}>JAG HAR HITTAT BÄRAREN</button></>}{stage===1&&<><div className="nfc-pulse">⌁</div><h3>Skanna den vandrande noden</h3><p>Håll mobilen mot NFC-taggen på ledarens nyckelband. Taggen kan lämnas vidare efter din skanning.</p><button className="primary full" onClick={()=>setStage(2)}>⌁ SIMULERA LEDARTAGG</button></>}{stage===2&&<><div className="transmission"><small>AVKODAD SÄNDNING</small><strong>16 · 1 · 18 · 11</strong></div><p>Varje tal motsvarar en bokstav i alfabetet. Vilket ord bildas?</p><div className="answer-grid">{["PORT","PARK","KODX","LANK"].map(a=><button key={a} onClick={()=>a==="PARK"?finish():setWrong(true)}>{a}</button>)}</div>{wrong&&<p className="error-note">Fel kod. Tips: A = 1, B = 2, C = 3…</p>}</>}</div>}
  {questId===2&&<div className="core-body">{stage===0&&<><p>Alla tre spelare måste bekräfta att de står vid sin tilldelade NFC-nod.</p><div className="player-ready">{ready.map((r,i)=><button key={i} className={r?"ready":""} onClick={()=>setReady(ready.map((v,n)=>n===i?!v:v))}><span>{r?"✓":i+1}</span><b>Spelare {i+1}</b><small>{r?"REDO":"VÄNTAR"}</small></button>)}</div><button className="primary full" disabled={!ready.every(Boolean)} onClick={()=>setStage(1)}>STARTA 10 SEKUNDERS FÖNSTER</button></>}{stage===1&&<><div className={`sync-clock ${count<=3?"danger":""}`}>{count}</div><p>Alla noder måste skannas innan tiden går ut.</p><div className="sync-nodes">{scans.map((s,i)=><button key={i} disabled={s||count<=0} className={s?"scanned":""} onClick={()=>scanNode(i)}>⌁<small>NOD {i+1}</small></button>)}</div>{count<=0&&<><p className="error-note">Tiden gick ut. Samla laget och försök igen.</p><button className="ghost full" onClick={resetSync}>BÖRJA OM</button></>}</>}</div>}
  {questId===3&&<div className="core-body">{stage===0&&<><div className="pixel-clue"><i/><i/><i/><i/><i/><i/><i/><i/><i/></div><p>Symbolen ovan finns gömd nära entrén. Hitta motsvarande NFC-bricka.</p><button className="primary full" onClick={()=>setStage(1)}>⌁ JAG HAR HITTAT BRICKAN</button></>}{stage===1&&<><h3>Vilken pixelväg är säker?</h3><p>Följ endast rutor som delar kant – aldrig hörn.</p><div className="path-options"><button onClick={()=>setWrong(true)}>A · ↘ ↘ →</button><button onClick={finish}>B · → ↓ →</button><button onClick={()=>setWrong(true)}>C · ↓ ↗ ↓</button></div>{wrong&&<p className="error-note">Glitch! Diagonala hopp räknas inte. Försök igen.</p>}</>}</div>}
  {questId===4&&<div className="core-body"><div className="raid-status"><span>LIVE EVENT</span><b>18/20 spelare anslutna</b></div><p>Tre energiceller måste aktiveras innan laget kan kombinera slutkoden.</p><div className="energy-cells">{cells.map((c,i)=><button key={i} className={c?"on":""} onClick={()=>setCells(cells.map((v,n)=>n===i?true:v))}><span>{c?"⚡":"○"}</span><b>CELL {i+1}</b><small>{c?"AKTIVERAD":"TRYCK FÖR NFC"}</small></button>)}</div>{cells.every(Boolean)&&<><div className="boss-code"><small>KODERNA BILDAR</small><strong>G · G · 7</strong></div><p>Välj rätt slutkod för att återställa Parkadens nätverk.</p><div className="answer-grid"><button onClick={()=>setWrong(true)}>G7G</button><button onClick={finish}>GG7</button><button onClick={()=>setWrong(true)}>7GG</button></div>{wrong&&<p className="error-note">Bossen blockerade koden. Läs cellerna från vänster till höger.</p>}</>}</div>}
  </>}</section></div>
}
