"use client";
import { useCallback,useEffect,useState } from "react";
import HintShop from "./HintShop";
import { acceptQuest,awardQuest } from "./game-progress";
import { getPlayer } from "./player-session";
type Q={id:number;sourceKey:string|null;title:string;type:string;description:string;place:string;steps:string;xp:number;hintCost:number;hintText:string;hintImageKey:string|null;startsAt:string|null;endsAt:string|null};
export default function LiveQuestFeed(){
  const[items,setItems]=useState<Q[]>([]),[selected,setSelected]=useState<Q|null>(null),[accepted,setAccepted]=useState<Set<number>>(new Set()),[completed,setCompleted]=useState<Set<number>>(new Set()),[busy,setBusy]=useState(false);
  const loadProgress=useCallback(()=>{const p=getPlayer();if(!p)return;fetch(`/api/progress?player=${encodeURIComponent(p.name)}`,{cache:"no-store"}).then(r=>r.json()).then(d=>{setAccepted(new Set((d.acceptances||[]).map((x:{questId:number})=>x.questId)));setCompleted(new Set((d.completions||[]).map((x:{questId:number})=>x.questId)))}).catch(()=>{})},[]);
  useEffect(()=>{fetch("/api/quests").then(async r=>{if(!r.ok)throw new Error("quests unavailable");return r.json()}).then(d=>setItems(d.quests||[])).catch(()=>setItems([]));loadProgress();window.addEventListener("progress-updated",loadProgress);return()=>window.removeEventListener("progress-updated",loadProgress)},[loadProgress]);
  if(!items.length)return null;const now=Date.now();
  const begin=async(q:Q)=>{setBusy(true);await acceptQuest(q);setAccepted(s=>new Set(s).add(q.id));setBusy(false);setSelected(q)};
  const finish=async(q:Q)=>{setBusy(true);const result=await awardQuest(q);if(result?.awarded||result?.completions){setCompleted(s=>new Set(s).add(q.id));setSelected(null)}setBusy(false)};
  return <><section className="live-quest-feed"><p className="eyebrow">ADMINPUBLICERADE UPPDRAG</p><h2>Live från spelledningen</h2><div className="live-quest-list">{items.map(q=>{const start=q.startsAt?new Date(q.startsAt).getTime():0,end=q.endsAt?new Date(q.endsAt).getTime():Infinity,upcoming=start>now,closed=end<now,done=completed.has(q.id),active=accepted.has(q.id);return <article key={q.id} className={upcoming||closed?"scheduled":done?"completed":"active"}><div><span>{q.type} · +{q.xp} Chip</span><h3>{q.title}</h3><p>{q.description}</p><small>⌖ {q.place||"Plats avslöjas i uppdraget"}</small>{q.startsAt&&<time>{upcoming?"STARTAR ":closed?"AVSLUTADES ":"AKTIVT SEDAN "}{new Date(q.startsAt).toLocaleString("sv-SE")}</time>}<button className="live-quest-action" disabled={upcoming||closed||done||busy} onClick={()=>active?setSelected(q):begin(q)}>{done?"SLUTFÖRT ✓":upcoming?"INTE STARTAT":closed?"AVSLUTAT":active?"FORTSÄTT UPPDRAG":"ANTA UPPDRAG"}</button></div>{!upcoming&&!closed&&!done&&<HintShop questId={q.id} cost={q.hintCost} text={q.hintText} imageKey={q.hintImageKey}/>}</article>})}</div></section>{selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="modal amber" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><p className="eyebrow">AKTIVT {selected.type}-UPPDRAG · +{selected.xp} Chip</p><h2>{selected.title}</h2><p>{selected.description}</p><div className="route-banner"><small>PLATS / RUTT</small><b>{selected.place||"Följ instruktionen från spelledningen"}</b></div><ol>{parseSteps(selected.steps).map(step=><li key={step}>{step}</li>)}</ol><button className="primary full" disabled={busy} onClick={()=>finish(selected)}>{busy?"REGISTRERAR…":"BEKRÄFTA ATT UPPDRAGET ÄR KLART"}</button><small className="completion-honesty">Bekräfta först när alla moment är utförda. Uppdraget kan bara ge Chip en gång.</small></section></div>}</>;
}
function parseSteps(raw:string){try{const a=JSON.parse(raw);return Array.isArray(a)&&a.length?a:["Följ uppdragsbeskrivningen","Genomför momentet på angiven plats","Bekräfta när allt är klart"]}catch{return["Följ uppdragsbeskrivningen","Genomför momentet på angiven plats","Bekräfta när allt är klart"]}}
