"use client";
import { useEffect, useRef, useState } from "react";
import QuestGames from "./QuestGames";
import CoreQuestGames from "./CoreQuestGames";
import MicGate from "./MicGate";
import SilenceQuest from "./SilenceQuest";
import LiveQuestFeed from "./LiveQuestFeed";
import LiveCommunity from "./LiveCommunity";
import PlayerXP from "./PlayerXP";
import { acceptQuest as persistAcceptance,awardQuest } from "./game-progress";
import XpAwardToast from "./XpAwardToast";
import CompletionLock from "./CompletionLock";
import PlayerOnboarding from "./PlayerOnboarding";
import TeamPanel from "./TeamPanel";

type Quest={id:number;type:"SOLO"|"LAG"|"EVENT";title:string;place:string;time:string;xp:number;people?:string;accent:string;icon:string;description:string;steps:string[]};
const defaultQuests:Quest[]=[
{id:1,type:"SOLO",title:"Den försvunna signalen",place:"Vandrande ledare",time:"8–15 min",xp:250,accent:"violet",icon:"⌁",description:"Signalbrickan sitter på en ledare och vandrar mellan personer under kvällen. Tolka den aktuella ledtråden, hitta rätt bärare och skanna innan signalen lämnas vidare.",steps:["Läs ledtråden om signalbäraren","Hitta ledaren i en tillåten publik zon","Skanna den vandrande NFC-taggen och knäck koden"]},
{id:2,type:"LAG",title:"Synkronisera nätverket",place:"Tre offentliga zoner",time:"12 min",xp:600,people:"3 spelare",accent:"cyan",icon:"⌘",description:"Tre spelare delar upp sig mellan kapphängningen i nedre foajén, den fejkade eldstaden i övre foajén och TV-spelsstationerna under läktaren.",steps:["Samla ett lag på tre","Ta varsin tilldelad publik zon","Skanna de tre noderna inom 10 sekunder"]},
{id:3,type:"SOLO",title:"Pixeljägaren",place:"Utomhus → nedre foajén",time:"7 min",xp:180,accent:"pink",icon:"◇",description:"Börja vid byggnadens entré utomhus, hitta pixelsymbolen längs fasaden och följ den vidare till soffgruppen i nedre foajén.",steps:["Hitta pixelsymbolen nära byggnaden","Skanna utomhusnoden","Lös pixelvägen vid soffgruppen i nedre foajén"]},
{id:4,type:"EVENT",title:"Boss raid: Blackout",place:"Skeppet",time:"20:00",xp:1200,people:"6–20 spelare",accent:"amber",icon:"⚡",description:"Kvällens raid utspelas i Skeppet. Energicellerna finns vid gradängens sällskapsspel, TV-hörnan och scenens publika sida – aldrig vid teknikbordet.",steps:["Samlas i Skeppet utan att blockera entréerna","Aktivera tre säkra energiceller","Kombinera slutkoden tillsammans"]}];
const quests=defaultQuests;
defaultQuests.push({id:5,type:"LAG",title:"Tyst kommunikation",place:"Övre foajéns hängyta",time:"Ingen tidsgräns",xp:450,people:"2 spelare",accent:"green",icon:"◉",description:"Sätt er vid sofforna nära den fejkade eldstaden. Ni får varsin del av en gåta och måste skriva in lösningen utan att prata.",steps:["Samlas vid övre foajéns soffor","Starta mikrofonkontrollen innan ledtråden visas","Kombinera ledtrådarna tyst och skriv rätt svar"]});
defaultQuests.push(
{id:6,type:"LAG",title:"Signalstafetten",place:"Nedre foajé → Skeppet",time:"10 min",xp:520,people:"3 spelare",accent:"orange",icon:"⇥",description:"För signalen från soffgruppen i nedre foajén, via den fejkade eldstaden på övervåningen, till sällskapsspelen vid gradängen i Skeppet.",steps:["Starta vid nedre foajéns soffgrupp","Aktivera eldstadsnoden i övre foajén","Avsluta vid gradängens sällskapsspel"]},
{id:7,type:"SOLO",title:"Minnesglitch",place:"TV-spel under läktaren",time:"4 min",xp:300,accent:"yellow",icon:"▦",description:"Skanna minnesnoden vid TV-spelsstationerna under läktaren. Memorera färgsekvensen och återskapa den i mobilen.",steps:["Hitta minnesnoden under läktaren","Memorera färgernas ordning","Återskapa sekvensen utan en ny titt"]},
{id:8,type:"SOLO",title:"Den falska noden",place:"Tre publika platser",time:"8 min",xp:360,accent:"red",icon:"△",description:"Samla påståenden vid kapphängningen, övre foajéns ståbord och TV-hörnan bredvid scenen. En nod ljuger.",steps:["Skanna de tre publika noderna","Jämför deras påståenden","Peka ut den falska noden"]},
{id:9,type:"LAG",title:"Hemlig agent",place:"Ledarbärare → TV-hörnan",time:"15 min",xp:480,people:"3–5 spelare",accent:"orange",icon:"?",description:"En spelare får ett dolt uppdrag från den vandrande ledartaggen och ska styra laget mot TV-hörnan utan att avslöja sin roll.",steps:["Hitta en ledare med den vandrande taggen","Öppna din hemliga roll diskret","Slutför uppdraget vid TV-hörnan"]},
{id:10,type:"EVENT",title:"Community unlock",place:"Alla publika zoner",time:"Pågår nu",xp:800,people:"Alla spelare",accent:"yellow",icon:"◎",description:"Unika skanningar utomhus, i båda foajéerna och i Skeppet laddar LAN-kärnan. Förbjudna och privata rum används aldrig.",steps:["Hitta en aktiv nod i en publik zon","Registrera en unik skanning","Hjälp hela LAN:et låsa upp bonusuppdraget"]}
);
const ideas=[["Stafett","Nästa NFC avslöjas först när lagkamraten klarat sin del."],["Tyst kommunikation","Två spelare får varsin halva av en gåta och får inte prata."],["Minnesglitch","Se en sekvens i fem sekunder – återskapa den vid nästa station."],["Falsk nod","Tre brickor ger ledtrådar, men en av dem ljuger."],["Hemlig agent","En spelare får ett dolt sidouppdrag mitt under lagets quest."],["Community unlock","Alla deltagares skanningar fyller en gemensam energimätare."]];
const communityUnlockAt:Record<number,number>={6:25,7:75,8:150,9:250,4:400};

export default function Home(){const[tab,setTab]=useState<"quests"|"map"|"team">("quests");const[filter,setFilter]=useState("ALLA");const[selected,setSelected]=useState<Quest|null>(null);const[joined,setJoined]=useState<number[]>([]);const[scanOpen,setScanOpen]=useState(false);const[silenceOpen,setSilenceOpen]=useState(false);const[communityScans,setCommunityScans]=useState(0);const[micState,setMicState]=useState<"ready"|"running"|"done"|"error">("ready");const[level,setLevel]=useState(0);const[seconds,setSeconds]=useState(30);const[warnings,setWarnings]=useState(0);const streamRef=useRef<MediaStream|null>(null);const rafRef=useRef<number|undefined>(undefined);const lastNoiseRef=useRef(0);const visible=quests.filter(q=>filter==="ALLA"||q.type===filter);const stopMic=()=>{streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;if(rafRef.current)cancelAnimationFrame(rafRef.current)};useEffect(()=>()=>stopMic(),[]);useEffect(()=>{const load=()=>fetch("/api/community",{cache:"no-store"}).then(r=>r.json()).then(d=>setCommunityScans(d.community?.scans||0)).catch(()=>{});load();window.addEventListener("community-scan",load);return()=>window.removeEventListener("community-scan",load)},[]);useEffect(()=>{if(micState!=="running")return;const timer=window.setInterval(()=>setSeconds(s=>s-1),1000);return()=>clearInterval(timer)},[micState]);useEffect(()=>{if(seconds<=0&&micState==="running"){stopMic();setMicState("done")}},[seconds,micState]);const startSilence=async()=>{try{stopMic();setSeconds(30);setWarnings(0);setLevel(0);const stream=await navigator.mediaDevices.getUserMedia({audio:true});streamRef.current=stream;const context=new AudioContext();const source=context.createMediaStreamSource(stream);const analyser=context.createAnalyser();analyser.fftSize=256;source.connect(analyser);const data=new Uint8Array(analyser.frequencyBinCount);setMicState("running");const measure=()=>{analyser.getByteFrequencyData(data);const average=data.reduce((a,b)=>a+b,0)/data.length;const next=Math.min(100,Math.round(average*2.2));setLevel(next);if(next>34&&Date.now()-lastNoiseRef.current>1100){setWarnings(w=>w+1);lastNoiseRef.current=Date.now()}rafRef.current=requestAnimationFrame(measure)};measure()}catch{setMicState("error")}};const closeSilence=()=>{stopMic();setSilenceOpen(false);setMicState("ready")};const acceptQuest=async(q:Quest)=>{const result=await persistAcceptance(q);if(!result?.accepted)return;setJoined(c=>c.includes(q.id)?c:[...c,q.id]);if(q.id===5){setSelected(null);setSilenceOpen(true)}};return <main><div className="noise"/><header className="topbar"><div className="brand"><span className="brandmark">GG</span><span>GOOD GAME <b>QUEST</b></span></div><div className="live"><i/> LIVE · PARKADEN</div><button className="avatar" aria-label="Öppna profil">B</button></header><div className="shell">
<PlayerOnboarding/><section className="status-card"><div><p className="eyebrow">HÖSTLOVET · HÄRNÖSAND</p><h1>Parkaden är<br/><em>spelplanen.</em></h1><p className="lead">Hitta signaler. Samla laget. Lös uppdragen.</p></div><PlayerXP/></section>
<LiveCommunity/><CompletionLock/>
<nav className="tabs" aria-label="Huvudnavigering"><button className={tab==="quests"?"active":""} onClick={()=>setTab("quests")}>Uppdrag <span>{quests.length}</span></button><button className={tab==="map"?"active":""} onClick={()=>setTab("map")}>Zoner</button><button className={tab==="team"?"active":""} onClick={()=>setTab("team")}>Mitt lag</button></nav>
{tab==="quests"&&<><div className="section-head"><div><p className="eyebrow">TILLGÄNGLIGA NU</p><h2>Välj nästa quest</h2></div><div className="filters">{["ALLA","SOLO","LAG","EVENT"].map(f=><button key={f} className={filter===f?"active":""} onClick={()=>setFilter(f)}>{f}</button>)}</div></div><section className="quest-grid">{visible.map(q=>{const at=communityUnlockAt[q.id],locked=Boolean(at&&communityScans<at);return <article className={`quest ${q.accent} ${locked?"community-locked":""}`} key={q.id} onClick={()=>{if(q.id===10){document.getElementById("community-core")?.scrollIntoView({behavior:"smooth"});return}if(!locked)setSelected(q)}}><div className="quest-top"><span className="quest-icon">{locked?"◈":q.icon}</span><span className="tag">{q.type}</span></div><h3>{q.title}</h3><p>{locked?`Hela LAN:et behöver nå ${at} unika NFC-skanningar för att låsa upp uppdraget.`:q.description}</p><div className="quest-meta"><span>⌖ {locked?"Platsen avslöjas vid upplåsning":q.place}</span><span>◷ {q.time}</span>{q.people&&<span>♟ {q.people}</span>}</div><footer><b>{locked?`${Math.max(0,at-communityScans)} skanningar kvar`:`+${q.xp} XP`}</b><span>{locked?`LÅSES VID ${at}`:q.id===10?"VISA COMMUNITY CORE ↑":joined.includes(q.id)?"ANTAGET ✓":"VISA UPPDRAG →"}</span></footer></article>})}</section><section className="idea-section"><p className="eyebrow">FLER SPELMEKANIKER</p><h2>Quest-idéer för hela byggnaden</h2><div className="idea-grid">{ideas.map(([title,text],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section></>}
{tab==="map"&&<section className="panel map-panel"><div><p className="eyebrow">SPELZONER</p><h2>Parkadens spelkarta</h2><p>Exakta NFC-positioner avslöjas först i ett aktivt uppdrag. Den vandrande noden kan byta ledare och röra sig mellan alla publika zoner.</p><div className="venue-restricted">FREDADE YTOR: sovsalar, toaletter, kök, matsal när den är stängd, låst kontor samt allt vid teknikbord, huvudrouter och admin.</div></div><div className="venue-map"><div className="venue-zone"><b>UTOMHUS</b><span>Entrén och byggnadens närmaste säkra fasadsida.</span></div><div className="venue-zone"><b>NEDRE FOAJÉ</b><span>Kapphängning och soffgrupp. Inga stationer inne på toaletter eller i sovsal.</span></div><div className="venue-zone"><b>ÖVRE FOAJÉ</b><span>Ståbord, fejkad eldstad och soffornas hängyta.</span></div><div className="venue-zone"><b>SKEPPET</b><span>Gradäng, kafé-/sällskapsspel, scenens publika sida, TV-hörna och TV-spel under läktaren.</span></div><div className="venue-zone mobile"><b>VANDRANDE NOD</b><span>NFC-taggen sitter på en ledare och kan lämnas vidare under kvällen.</span></div></div></section>}
{tab==="team"&&<TeamPanel/>}</div>
<div className="dynamic-feed-wrap"><LiveQuestFeed/></div>
<button className="scan-button" onClick={()=>setScanOpen(true)}><span>⌁</span> SKANNA NFC</button>
{selected&&selected.id<=4&&joined.includes(selected.id)?<CoreQuestGames questId={selected.id} onClose={()=>setSelected(null)} onComplete={()=>{setJoined(c=>c.includes(selected.id)?c:[...c,selected.id]);awardQuest(selected)}}/>:selected&&selected.id>=6&&joined.includes(selected.id)?<QuestGames questId={selected.id} onClose={()=>setSelected(null)} onComplete={()=>{setJoined(c=>c.includes(selected.id)?c:[...c,selected.id]);awardQuest(selected)}}/>:selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className={`modal ${selected.accent}`} onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><span className="quest-icon large">{selected.icon}</span><p className="eyebrow">{selected.type} QUEST · {selected.xp} GRUND-XP + TIDSBONUS</p><h2>{selected.title}</h2><p>{selected.description}</p><ol>{selected.steps.map(s=><li key={s}>{s}</li>)}</ol><div className="time-xp-note"><b>⏱ TIDEN STARTAR NÄR DU ANTAR</b><span>Snabbare lösning ger upp till 50 % extra XP. Du behåller alltid uppdragets grundpoäng.</span></div><button className="primary full" onClick={()=>acceptQuest(selected)}>{selected.id===5?"ANTA & STARTA TYSTNADSUPPDRAG":"ANTA & STARTA TIDEN"}</button></section></div>}
<XpAwardToast/><MicGate/>{silenceOpen&&<SilenceQuest onClose={closeSilence} onComplete={()=>{setJoined(c=>c.includes(5)?c:[...c,5]);awardQuest(quests[4])}}/>}
{scanOpen&&<div className="modal-backdrop" onClick={()=>setScanOpen(false)}><section className="scan-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setScanOpen(false)}>×</button><div className="scan-rings"><span>⌁</span></div><p className="eyebrow">NFC-LÄSARE REDO</p><h2>Håll mobilen mot brickan</h2><p>På en riktig station öppnas rätt quest direkt via brickans unika webblänk.</p><button className="ghost" onClick={async()=>{await fetch("/api/community",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({playerName:"Björnler",xpGain:20})});const progress=await fetch("/api/progress?player=Björnler",{cache:"no-store"}).then(r=>r.json());window.dispatchEvent(new Event("community-scan"));window.dispatchEvent(new Event("progress-updated"));setScanOpen(false);if((progress.completions||[]).some((q:{questId:number})=>q.questId===1)){window.alert("Den försvunna signalen är redan slutförd. Välj ett annat uppdrag.");return}setSelected(quests[0])}}>SIMULERA SKANNING · +20 XP</button></section></div>}</main>}
