"use client";
import { useEffect, useState } from "react";

type Props={questId:number;onClose:()=>void;onComplete:()=>void};
const COLORS=["orange","yellow","red","blue"];

export default function QuestGames({questId,onClose,onComplete}:Props){
  const[step,setStep]=useState(0);const[done,setDone]=useState(false);const[showMemory,setShowMemory]=useState(true);const[memoryInput,setMemoryInput]=useState<string[]>([]);const[energy,setEnergy]=useState(68);const[roleOpen,setRoleOpen]=useState(false);
  const sequence=["orange","red","yellow","blue"];
  useEffect(()=>{if(questId!==7)return;const t=setTimeout(()=>setShowMemory(false),3500);return()=>clearTimeout(t)},[questId]);
  const finish=()=>{setDone(true);onComplete()};
  const memoryTap=(color:string)=>{const next=[...memoryInput,color];setMemoryInput(next);if(sequence[next.length-1]!==color){setTimeout(()=>setMemoryInput([]),500)}else if(next.length===sequence.length)finish()};
  const titles:{[key:number]:string}={6:"Signalstafetten",7:"Minnesglitch",8:"Den falska noden",9:"Hemlig agent",10:"Community unlock"};
  const routes:{[key:number]:string}={6:"Nedre foajéns soffor → fejkade eldstaden → sällskapsspelen vid gradängen",7:"TV-spelsstationerna under läktaren",8:"Kapphängningen → övre foajéns ståbord → TV-hörnan",9:"Vandrande ledartagg → TV-hörnan bredvid scenen",10:"Utomhus + båda foajéerna + publika delar av Skeppet"};
  return <div className="modal-backdrop"><section className="game-modal"><button className="close" onClick={onClose}>×</button><p className="eyebrow">LIVE QUEST · {questId===10?"ALLA SPELARE":"AKTIVT UPPDRAG"}</p><h2>{titles[questId]}</h2><div className="route-banner"><small>UPPDRAGSRUTT</small><b>{routes[questId]}</b><span>Inga spelmoment placeras i sovsalar, toaletter, kök, låst kontor eller vid teknik/admin.</span></div>
  {done&&<div className="game-result"><div className="result-mark success">✓</div><h3>Quest slutförd!</h3><p>Din insats är registrerad och poängen har lagts till.</p><button className="primary full" onClick={onClose}>TILLBAKA TILL QUESTS</button></div>}
  {!done&&questId===6&&<div className="game-body"><div className="stage-track"><i className={step>=0?"active":""}/><i className={step>=1?"active":""}/><i className={step>=2?"active":""}/></div><span className="game-kicker">STATION {step+1} AV 3</span><div className="station-code">{["A7","K2","X9"][step]}</div><h3>{["Start vid soffgruppen","Eldstadsnoden väntar","Slutnod i Skeppet"][step]}</h3><p>{["Skanna vid soffgruppen i nedre foajén och visa koden för nästa lagkamrat.","Gå upp till den fejkade eldstaden. Skanna utan att blockera vägen mot Skeppet.","Avsluta tillsammans vid sällskapsspelen intill gradängen i Skeppet."][step]}</p><button className="primary full" onClick={()=>step<2?setStep(step+1):finish()}>⌁ SIMULERA NFC-SKANNING</button></div>}
  {!done&&questId===7&&<div className="game-body"><p>{showMemory?"Memorera sekvensen. Den försvinner snart.":"Återskapa färgsekvensen i rätt ordning."}</p><div className="memory-grid">{COLORS.map((c,i)=><button key={c} disabled={showMemory} className={`${c} ${showMemory&&sequence[i]===c?"flash":""} ${memoryInput.includes(c)?"pressed":""}`} onClick={()=>memoryTap(c)} aria-label={c}/>)}</div><div className="memory-progress">{sequence.map((_,i)=><i key={i} className={memoryInput[i]?"filled":""}/>)}</div>{showMemory&&<strong className="countdown-note">SEKVENS AKTIV</strong>}</div>}
  {!done&&questId===8&&<div className="game-body"><p>Tre NFC-noder gav varsin uppgift. Två talar sanning. Vilken nod ljuger?</p><div className="node-list"><button onClick={()=>setStep(1)}><b>NOD A</b><span>”Koden är ett jämnt tal.”</span></button><button onClick={finish}><b>NOD B</b><span>”Koden är större än 8.”</span></button><button onClick={()=>setStep(1)}><b>NOD C</b><span>”Koden är 6.”</span></button></div>{step===1&&<p className="error-note">Inte den noden. Jämför alla tre påståenden igen.</p>}</div>}
  {!done&&questId===9&&<div className="game-body">{!roleOpen?<><div className="secret-card"><span>?</span><small>VANDRANDE LEDARTAGG</small></div><p>Hitta ledaren som bär taggen just nu. Skanna diskret och se till att ingen annan tittar på skärmen.</p><button className="primary full" onClick={()=>setRoleOpen(true)}>⌁ SIMULERA LEDARTAGG</button></>:<><div className="role-card"><small>DIN HEMLIGA ROLL</small><h3>THE GLITCH</h3><p>Få laget att självmant ta sig till TV-hörnan bredvid scenen utan att avslöja ditt sidouppdrag.</p></div><button className="primary full" onClick={finish}>UPPDRAG UTFÖRT VID TV-HÖRNAN</button></>}</div>}
  {!done&&questId===10&&<div className="game-body"><div className="energy-ring" style={{"--energy":`${energy*3.6}deg`} as React.CSSProperties}><strong>{energy}%</strong><span>GLOBAL ENERGI</span></div><h3>{energy<100?"Hela LAN:et laddar kärnan":"KÄRNAN ÄR UPPLÅST"}</h3><p>{energy<100?"Varje unik NFC-skanning bidrar. Din skanning fyller energin för alla spelare.":"Alla bidrog – kvällens bonusquest är nu tillgängligt!"}</p><button className="primary full" disabled={energy>=100} onClick={()=>{const n=Math.min(100,energy+12);setEnergy(n);if(n===100)setTimeout(finish,700)}}>{energy>=100?"UPPLÅST":"⌁ REGISTRERA MIN NFC"}</button></div>}
  </section></div>
}
