"use client";
import { FormEvent, useEffect, useRef, useState } from "react";
type Props={onClose:()=>void;onComplete:()=>void};
export default function SilenceQuest({onClose,onComplete}:Props){
  const[state,setState]=useState<"starting"|"running"|"failed"|"done"|"error">("starting");const[level,setLevel]=useState(0);const[strikes,setStrikes]=useState(0);const[answer,setAnswer]=useState("");const[wrong,setWrong]=useState(false);const stream=useRef<MediaStream|null>(null);const frame=useRef<number|undefined>(undefined);const lastStrike=useRef(0);const active=useRef(false);
  const stop=()=>{active.current=false;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(frame.current)cancelAnimationFrame(frame.current)};
  const start=async()=>{stop();setState("starting");setStrikes(0);setLevel(0);setAnswer("");setWrong(false);try{const media=await navigator.mediaDevices.getUserMedia({audio:true});stream.current=media;const context=new AudioContext();const source=context.createMediaStreamSource(media);const analyser=context.createAnalyser();analyser.fftSize=256;source.connect(analyser);const data=new Uint8Array(analyser.frequencyBinCount);active.current=true;setState("running");const measure=()=>{if(!active.current)return;analyser.getByteFrequencyData(data);const avg=data.reduce((a,b)=>a+b,0)/data.length;const next=Math.min(100,Math.round(avg*2.2));setLevel(next);if(next>34&&Date.now()-lastStrike.current>1100){lastStrike.current=Date.now();setStrikes(s=>{const value=s+1;if(value>=4){stop();setState("failed")}return value})}if(active.current)frame.current=requestAnimationFrame(measure)};measure()}catch{setState("error")}};
  useEffect(()=>{start();return()=>stop()},[]);
  const submit=(e:FormEvent)=>{e.preventDefault();const normalized=answer.trim().toUpperCase().replaceAll(" ","");if(normalized==="BLÅ7"||normalized==="BLA7"){stop();setState("done");onComplete()}else setWrong(true)};const close=()=>{stop();onClose()};
  return <div className="modal-backdrop"><section className="silence-modal locked"><button className="close" onClick={close}>×</button><p className="eyebrow">LAGQUEST · TYST KOMMUNIKATION</p>{state==="starting"&&<div className="mic-starting"><div className="nfc-pulse">◉</div><h2>Mikrofonen startar…</h2><p>Ledtråden visas först när ljudkontrollen är aktiv.</p></div>}{state==="running"&&<><h2>Klura utan ett ord.</h2><div className="clue-card live-clue"><small>DIN DEL AV LEDTRÅDEN · VISA INTE</small><strong>FÄRGEN FINNS OVANFÖR MOLNEN</strong></div><p className="partner-note">Din lagkamrat har den andra delen. Kombinera delarna och skriv in lösningen – utan att prata.</p><div className="live-audio"><div className={`mic-dot ${level>34?"loud":""}`}>◉</div><div><b>{level>34?"FÖR HÖGT!":"MIKROFONEN LYSSNAR"}</b><div className="meter"><i style={{width:`${level}%`}}/></div></div></div><div className="strike-row">{[0,1,2,3].map(i=><i key={i} className={i<strikes?"hit":""}>!</i>)}</div><small className="strike-help">Fyra ljudvarningar avbryter uppdraget</small><form className="silent-answer" onSubmit={submit}><label htmlFor="silent-code">LAGETS SVAR</label><input id="silent-code" value={answer} onChange={e=>{setAnswer(e.target.value);setWrong(false)}} placeholder="Skriv lösningen här" autoComplete="off"/><button className="primary full" type="submit" disabled={!answer.trim()}>LÅS SVARET</button></form>{wrong&&<p className="error-note">Det är inte rätt lösning. Fortsätt klura – och håll er tysta.</p>}</>}{state==="failed"&&<><div className="result-mark warn">!</div><h2>För mycket ljud</h2><p>Fyra ljudvarningar registrerades. Försöket avbröts och ledtråden låstes.</p><button className="primary full" onClick={start}>STARTA OM FRÅN BÖRJAN</button></>}{state==="done"&&<><div className="result-mark success">✓</div><h2>Rätt svar!</h2><p>Ni kombinerade ledtrådarna och löste uppdraget utan att prata.</p><button className="primary full" onClick={close}>HÄMTA 450 XP</button></>}{state==="error"&&<><div className="result-mark warn">!</div><h2>Mikrofonen är inte tillgänglig</h2><p>Ledtråden förblir dold tills mikrofonen är aktiv.</p><button className="ghost full" onClick={start}>FÖRSÖK IGEN</button></>}</section></div>}
